/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string.h>
#include <stdio.h>
#include <android/log.h>
#include <android/bitmap.h>

#include <libavcodec/avcodec.h>
#include <libavformat/avformat.h>
#include <libswscale/swscale.h>
#include <libavformat/avio.h>
/* Header for class com_example_titants_videoselection_util_TrimVideoFFmpeg */

#ifndef _Included_com_example_titants_videoselection_util_TrimVideoFFmpeg
#define _Included_com_example_titants_videoselection_util_TrimVideoFFmpeg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_titants_videoselection_util_TrimVideoFFmpeg
 * Method:    naTrimVideo
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_titants_videoselection_util_TrimVideoFFmpeg_naTrimVideo
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint);


//PRIVATE METHOD
static int openFile(AVFormatContext **pFormatContext, const char *cPath);
static int getCodecVideo(AVFormatContext *pFormatCtx, AVCodecContext **pCodecCtx, AVCodecContext **pCodecCtxOrig, AVCodec **pCodec);
static int convert_and_cut(const char *file, float starttime, float endtime);


#ifdef __cplusplus
}
#endif
#endif
